version: '3'
services:
  neoj4:
    image: neo4j:3.5
    container_name: "arquie-neo4j"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
    ports:
      - "7687:7687"
      - "7474:7474"
